### PR TITLE
Adding !josch-Command

### PR DESCRIPTION
**Pull request by f0xit**

### CODE REVIEW

**Comment by patti2** [comment]
+1 for this important feature
cc @josch700

**Comment by josch700** [comment]
+10
extremly important actually

**Review by PSDevChris — COMMENTED** [review]
`@commands.command(name="Josch", aliases="josch")
    async def _entwicklerbestrafen(self, ctx):
        await ctx.send(file=discord.File('josch.png'))`

should be

`@commands.command(name="Josch", aliases="josch")
    async def _entwicklerbestrafen(self, ctx):
        await ctx.send(file=discord.File('/memes/josch700#3680/josch.png'))`

to be in line with the tagging meme gallery. 

PNG file will be added, but the bot does not ship with the meme gallery, so it is unnecessary here.

**Comment by PSDevChris** [comment]
Command added.

**Pull request merged**
